### ISSUE TITLE
Build fails during spooles build

### ISSUE THREAD

**Issue by fklaenfoth** [costerwi/homebrew-calculix#4]
I tried to install ccx using the homebrew formula ([Failure logs in Gist](https://gist.github.com/pheluxe/ca11abf56f6909ea8599eb3754c92c70)).
The build fails as far as I can tell while building spooles. I have little experience with C and therefore find it difficult to assess the error. There seems to be a problem with the definition of NULL on my system. Is this a problem with spooles or with my configuration? How can I fix this? I am grateful for any help you can give me.

**Comment by costerwi** [comment]
I'm not sure what but something has recently changed which flags the spooles error.

I think I found and the problem in spooles with a new patch.

Let me know if this works for you too.

**Comment by fklaenfoth** [comment]
Perfect! After a brew cleanup the build was successful. This resolves the issue. Thank you very much!
